In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split 

In [86]:
!pip install scikit-learn

In [8]:
array1 = np.array([1,2,3])
print("array1 type :" , type(array1))
print("array1 array 형태 :", array1.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)


In [10]:
array2 = np.array([[1,2,3],[2,3,4]])
print("arry2 type :", type(array2))
print ("arry2 array 형태 :", array2.shape )

arry2 type : <class 'numpy.ndarray'>
arry2 array 형태 : (2, 3)


In [12]:
array3 = np.array([[1,2,3]])
print("array3 type : ", type(array3))
print("array3 array 형태: ", array3.shape)

array3 type :  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [15]:
print('array1: {0}차원, array2 : {1}차원 , array3 : {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2 : 2차원 , array3 : 2차원


In [23]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1 , array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [24]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [27]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [28]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float , array_float.dtype)

[1. 2. 3.] float64


In [30]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [31]:
array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [33]:
seqeunce_array = np.arange(10)
print(seqeunce_array)
print(seqeunce_array, seqeunce_array.dtype, seqeunce_array.shape) 

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] int32 (10,)


In [38]:
zero_array = np.zeros((3,2), dtype = ('int32'))
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [39]:
one_array = np.ones((3,2), dtype = ('int32'))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


In [41]:
array1 = np.arange(10)
print("array1:\n" , array1) # \n 의 값 줄 바꾸기 

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [42]:
array2 = array1.reshape(5,2)
print('array2 : \n' , array2)

array2 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [43]:
array3 = array1.reshape(2,5)
print('array3 :\n', array3)

array3 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [55]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5) # 10개의 데이터 이기에 -1(2)
print("array2 shape:", array2.shape) 
array3= array1.reshape(5,-1) # 10개의 데이터 이기에 -1(2)
print("array3 shape:", array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [56]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('arrray3d:\n', array3d.tolist()) 

arrray3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [61]:
# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1) 
print('array5 : \n', array5.tolist()) # 8행 1열
print(array5.shape)

array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [63]:
# 1차원 ndarray를 2차원 ndarray 로 변환
array6 = array1.reshape(-1,1)
print('array6 :\n', array6.tolist())
print(array6.shape)

array6 :
 [[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [64]:
# 1 ~ 9 까지 1차원 ndarray 생성

array1 = np.arange(start=1, stop=10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [66]:
# index는 0부터 시작흐므로 array1[2]는 3번쨰 index 위치의 데이터 값을 의미
value = array1[2]
print(value)
print(type(value))

3
<class 'numpy.int32'>


In [67]:
array1[0]=9
array1[0]

9

In [68]:
array1d = np.arange(start = 1, stop= 10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
array2d[2,2]

9

In [75]:
# 패싱 인덱싱
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())


array2d[[0,1],2] => [3, 6]


In [76]:
array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array2d[[0,1],0:2] => [[1, 2], [4, 5]]


In [77]:
array5= array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [78]:
# 불린 인덱싱 
array1d = np.arange(start=1, stop = 10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용

array3 = array1d[array1d>5] 
print('array1d > 5 불린 인덱싱 결과 값 :', array3 ) # 결과값과 의 숫자의 조건이 아닌 인덱스 숫자의 조건이다. 

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [80]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [82]:
boolean_index = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_index]
print('불린 인덱스로 필터링 결과 :', array3) # - 동일한 결과가 나온다. 

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [87]:
org_array = np.array([3,1,9,5])
print('원본 행렬: ', org_array)

원본 행렬:  [3 1 9 5]


In [89]:
# np.sort( )로 정렬 - 순서 대로 출력 
sort_array1 = np.sort(org_array)
print(sort_array1) 

[1 3 5 9]


In [93]:
# ndarray.sort() 로 정렬
sort_array2 = org_array.sort()
print(sort_array2)

None


In [98]:
# 내림차순으로 출력 = [::-1]
sort_array1 = np.sort(org_array)[::-1]
print(sort_array1)

[9 5 3 1]


In [99]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print(sort_array2d_axis0)

[[ 7  1]
 [ 8 12]]


In [101]:
sort_array2d_axis1 = np.sort(array2d, axis = 1)
print(sort_array2d_axis1)

[[ 8 12]
 [ 1  7]]


In [102]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices) # 인덱스의 숫자만 출력. - 순서에 대해서 

<class 'numpy.ndarray'>
[1 0 3 2]


In [103]:
# 반대로 내림 차순으로 출력 [::-1]

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)[::-1]
print(type(sort_indices))
print(sort_indices) # 인덱스의 숫자만 출력. - 순서에 대해서 

<class 'numpy.ndarray'>
[2 3 0 1]


In [106]:
# argsort 활용 

name_array = np.array(['John', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'sarah' 'samuel' 'mike' 'kate']


In [108]:
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat) 

[[1 3]
 [2 4]]
